# Configuration file to declaratively configure labels
# Ref: https://github.com/EndBug/label-sync#Config-files

- name: area/kustomize
  description: Kustomize related issues and pull requests
  color: '#00e54d'
- name: area/kstatus
  description: Health checking related issues and pull requests
  color: '#25D5CA'
  aliases: ['area/health-checks']
- name: area/sops
  description: SOPS related issues and pull requests
  color: '#FEE5D1'
- name: area/server-side-apply
  description: SSA related issues and pull requests
  color: '#2819CB'
- name: area/varsub
  description: Post-build variable substitution related issues and pull requests
  color: '#8D195D'
- name: backport:release/v1.0.x
  description: To be backported to release/v1.0.x
  color: '#ffd700'
- name: backport:release/v1.1.x
  description: To be backported to release/v1.1.x
  color: '#ffd700'
- name: backport:release/v1.2.x
  description: To be backported to release/v1.2.x
  color: '#ffd700'
- name: backport:release/v1.3.x
  description: To be backported to release/v1.3.x
  color: '#ffd700'
- name: backport:release/v1.4.x
  description: To be backported to release/v1.4.x
  color: '#ffd700'
- name: backport:release/v1.5.x
  description: To be backported to release/v1.5.x
  color: '#ffd700'
- name: backport:release/v1.6.x
  description: To be backported to release/v1.6.x
  color: '#ffd700'
- name: backport:release/v1.7.x
  description: To be backported to release/v1.7.x
  color: '#ffd700'
